import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar/NavBar";
import '@fortawesome/fontawesome-free/css/all.css'
import Footer from "./_components/Footer/Footer";
import BackGround from "./(main)/backGround/backGround";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GameVault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <NavBar/>

      

       <main className="bg-sec">
         {children}
       </main>

       <Footer/>
      </body>
    </html>
  );
}
